CREATE TABLE IF NOT EXISTS pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    notion_page_id VARCHAR(255) NOT NULL UNIQUE,
    notion_parent_page_id VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    icon VARCHAR(255),
    url VARCHAR(255) NOT NULL,
    CONSTRAINT pages_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
